feat: 🎸 already client question add to quotation form
equipementmoderne/magasin-global pull request #126
Opened 2023-04-07 07:46 UTC by LeaCtrlup

✅ Closes: 120

2023-04-07 09:33 UTC, quibaritaenperdresatrompe commented on src/routes/products-quotation.tsx
> +          <RadioGroup
Est-ce que tu as étudié la possibilité d'utiliser un composant [`<Switch>`](https://mui.com/material-ui/react-switch/) à la place ?

2023-04-07 09:33 UTC, quibaritaenperdresatrompe commented on src/routes/products-quotation.tsx
> +            <FormControlLabel value="oui" control={<Radio />} label="Oui" />
C'est dangereux de gérer une valeur au format `string` alors qu'on a besoin d'un booléen. Ici les valeurs doivent êtres `true` ou `false`.

2023-04-07 09:33 UTC, quibaritaenperdresatrompe commented on src/routes/products-quotation.tsx
>  import { Quotation } from "../types/product";
N'avons-nous pas besoin d'ajouter une prop au type `Quotation` ?

2023-04-07 09:36 UTC, LeaCtrlup commented on src/routes/products-quotation.tsx
> +          <RadioGroup
non quand j'ai lu ta description sur le ticket il m'a semblé clair que c'était un ToggleButton
"Le formulaire de demande de devis permet de spécifier si on est déjà client à l'aide d'un champ booléen."
J'ai pu me tromper dans ma compréhension mais du coup, je trouve quand même plus classique/clair le fait de mettre un ToggleButton

2023-04-07 09:37 UTC, LeaCtrlup commented on src/routes/products-quotation.tsx
> +            <FormControlLabel value="oui" control={<Radio />} label="Oui" />
oui c'est vrai

2023-04-07 11:14 UTC, quibaritaenperdresatrompe commented on src/routes/products-quotation.tsx
> +          <RadioGroup
C'est bien quelque chose comme cela que tu as mis ? 
![image](https://user-images.githubusercontent.com/26886259/230599458-cbd1e327-7346-492b-b4ba-d20ca757f255.png)

Si oui alors c'est un input de type "radio" et non un ToggleButton.
L'input de type "radio" ne me semble pas adapté à un type booléen. En revanche le ToggleButton peut être une meilleure solution que le Switch car plus en accord avec notre UI. :+1: 
![image](https://user-images.githubusercontent.com/26886259/230599675-37dfe7fb-b647-4040-b0f8-f6ae3acf86b4.png)

2023-04-07 13:16 UTC, quibaritaenperdresatrompe commented on src/components/BoolInput.tsx
> +const booleanObject = {
on peut appeler cet objet `options` :v:

2023-04-07 13:16 UTC, quibaritaenperdresatrompe commented on src/components/BoolInput.tsx
> +const BoolInput = forwardRef(function BoolInput(
Le composant peut s'appeler `BooleanInput`

2023-04-07 13:16 UTC, quibaritaenperdresatrompe commented on src/routes/products-quotation-test.tsx
> +    expect(screen.getByText("Etes-vous déjà client ?")).toBeInTheDocument();
plutôt un `getByTestId` ici nope ?

2023-04-07 13:16 UTC, quibaritaenperdresatrompe commented on src/routes/products-quotation.tsx
> +          <Typography>Etes-vous déjà client ?</Typography>
Ne devrait-on pas faire porter le label au composant `BooleanInput` avec un FormControl et InputLabel comme dans PasswordInput ?

2023-04-07 13:16 UTC, quibaritaenperdresatrompe commented on src/types/product.ts
> +  alreadyClient: boolean;
`isClient` est peut être plus court :shrug:

2023-04-07 13:16 UTC, quibaritaenperdresatrompe commented on src/utils/createQuotationEmail.tsx
> +        alreadyClient ? "déjà client" : "pas encore client"
Je n'aurais mis la mention que dans le cas où c'est un client, nope ?

2023-04-07 14:09 UTC, LeaCtrlup commented on src/routes/products-quotation-test.tsx
> +    expect(screen.getByText("Etes-vous déjà client ?")).toBeInTheDocument();
le composant n'accepte pas de prop inputProps donc je ne peux pas rajouter de test-id

2023-04-07 14:15 UTC, LeaCtrlup commented on src/routes/products-quotation.tsx
> +          <Typography>Etes-vous déjà client ?</Typography>
avec le FormControl nous avons une ui comme ceci 
![image](https://user-images.githubusercontent.com/110475531/230623801-d62a151b-7fc0-4e9b-8783-2c8ed5155f49.png)

2023-04-07 14:16 UTC, LeaCtrlup commented on src/routes/products-quotation.tsx
> +          <Typography>Etes-vous déjà client ?</Typography>
puisque le label est sensé se retrouver dans l'input, je ne suis pas sûre que ce soit ce qu'il faut utiliser dans notre cas

2023-04-07 14:20 UTC, quibaritaenperdresatrompe commented on src/routes/products-quotation.tsx
> +          <Typography>Etes-vous déjà client ?</Typography>
Pourtant ça fonctionne bien pour `StateInput` ..? :thinking:

2023-04-07 14:20 UTC, quibaritaenperdresatrompe commented on src/routes/products-quotation-test.tsx
> +    expect(screen.getByText("Etes-vous déjà client ?")).toBeInTheDocument();
L'attribut data-testid est recevable par n'importe quel composant qui dépose ces props en attributs html

2023-04-07 14:21 UTC, quibaritaenperdresatrompe commented on src/routes/products-quotation-test.tsx
> +    expect(screen.getByText("Etes-vous déjà client ?")).toBeInTheDocument();
Et si on bascule le label dans le composant BooleanInput alors on ne testera plus le rendu du label ici mais dans le test du composant :v:

2023-04-07 14:40 UTC, LeaCtrlup commented on src/routes/products-quotation.tsx
> +          <Typography>Etes-vous déjà client ?</Typography>
je n'ai pas vu de toggle qui ait de label, c'est le seul que l'on ait je crois. StateInput n'a ni InputLabel ni FormControl

2023-04-07 15:21 UTC, quibaritaenperdresatrompe commented on src/routes/products-quotation.tsx
> +          <Typography>Etes-vous déjà client ?</Typography>
Le StateInput et StatusInput sont des ToggleButton...

2023-04-07 15:38 UTC, LeaCtrlup commented on src/routes/products-quotation.tsx
> +          <Typography>Etes-vous déjà client ?</Typography>
je crois que tu as mal lu mon message, je n'ai pas dit que StateInput et StatusInput n'était pas des ToggleButton

2023-04-11 09:20 UTC, quibaritaenperdresatrompe requested changes

2023-04-11 10:15 UTC, quibaritaenperdresatrompe approved these changes

2023-04-11 12:32 UTC, merged

2023-04-11 12:36 UTC, quibaritaenperdresatrompe commented
:tada: This PR is included in version 1.36.0 :tada:

The release is available on [GitHub release](https://github.com/equipementmoderne/magasin-global/releases/tag/v1.36.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: