fix: 🐛 change simplified states management
equipementmoderne/magasin-global pull request #127
Opened 2023-04-07 08:43 UTC by LeaCtrlup

✅ Closes: 115

2023-04-07 09:35 UTC, quibaritaenperdresatrompe commented on src/routes/products.tsx
> -      state: state === State.Used ? [State.DCN, State.DVO] : state,
Tu as besoin de continuer à faire le mapping pour les états simplifiés dans le cas d'un utilisateur non-connectés. I.e. que pour un utilisateur connecté qui n'a que deux options de filtrer "Neuf" et "Occasion" alors 'il faut bien filtrer sur les produits "Neuf" et "DVN" quand l'option "Neuf" est choisie.

2023-04-07 13:22 UTC, quibaritaenperdresatrompe requested changes

2023-04-07 13:22 UTC, quibaritaenperdresatrompe commented on src/routes/products.tsx
> +      return state;
1. j'aurais fais le cas où il y a le user.id au débu de l'algo
2. pas besoin de tester si le state existe

ce qui donne un algo plus simple :

```js
const simplifyState = state => {
  if (state === State.Used) return [State.Used, State.DVO]; 
  if (state === State.New) return [State.New, State.DCN];
  return state;
}

const filters = { state: user.id ? state : simplifyState(state) }
```

2023-04-07 13:22 UTC, quibaritaenperdresatrompe commented on src/routes/products.tsx
> +  const productState = useCallback(() => {
le useCallback sert à mémoiser des functions et non des constantes...

2023-04-07 13:33 UTC, LeaCtrlup commented on src/routes/products.tsx
> +  const productState = useCallback(() => {
productState est une fonction pourtant

2023-04-07 14:22 UTC, quibaritaenperdresatrompe commented on src/routes/products.tsx
> +  const productState = useCallback(() => {
ça ne devrait pas être une méthode ou alors il faut l'extraire du composant et à ce moment là il n'y aura plus besoin de mémoiser

2023-04-07 14:42 UTC, quibaritaenperdresatrompe approved these changes

2023-04-07 14:42 UTC, quibaritaenperdresatrompe commented on src/routes/products.tsx
> +    [category, state, user, status, subCategory]
Est-ce qu'on aurait pas un dépendances à `user?.id` plutôt que `user` ?

2023-04-07 14:42 UTC, quibaritaenperdresatrompe commented on src/routes/products.tsx
> +import { useMemo, MouseEvent, useState, useCallback } from "react";
Tu as import non-utilisé ici :wink:

2023-04-07 15:21 UTC, quibaritaenperdresatrompe approved these changes

2023-04-11 07:23 UTC, merged

2023-04-11 07:28 UTC, quibaritaenperdresatrompe commented
:tada: This PR is included in version 1.34.1 :tada:

The release is available on [GitHub release](https://github.com/equipementmoderne/magasin-global/releases/tag/v1.34.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: