feat: 🎸 search products in products list thanks to seach bar
equipementmoderne/magasin-global pull request #89
Opened 2023-03-29 12:03 UTC by LeaCtrlup

✅ Closes: #21

2023-03-29 15:54 UTC, quibaritaenperdresatrompe commented
Le préfixe de commit `style` est pour le style du code et non de l'UI. Ici ça serait plutôt un `fix` ou `feat`.

2023-03-29 15:54 UTC, quibaritaenperdresatrompe commented on src/routes/products.tsx
> +import { TextField } from "@mui/material";
On doit utiliser des imports par défaut : `import TextField from "@mui/material/TextField";`

2023-03-29 16:01 UTC, quibaritaenperdresatrompe commented on src/utils/search.test.ts
> +  it("returns four category products when `four` is the default term", () => {
> `four category`
Pourquoi `four` ? C'est 4 ?
Pourquoi `category` ?

Ici il faut s'abstraire de la notion de `product`.

2023-03-29 16:01 UTC, quibaritaenperdresatrompe commented on src/utils/search.test.ts
> +  it("returns products containing all searched key words", () => {
Ici il faut s'abstraire de la notion de `product`.

2023-03-30 06:40 UTC, LeaCtrlup commented on src/routes/products.tsx
> +import { TextField } from "@mui/material";
ah oui c'est de l'auto import ça je pense, je change ça

2023-03-30 06:46 UTC, LeaCtrlup commented on src/routes/products.tsx
> +  const data = search<Product>(query.data, searchedTerm, [
je ne sais pas, ça ne va pas poser de problème vu qu'on souhaite justement que la data évolue à chaque fois que l'on modifie l'input ?

2023-03-30 07:11 UTC, quibaritaenperdresatrompe commented on src/routes/products.tsx
> +  const data = search<Product>(query.data, searchedTerm, [
C'est pour ça qu'un `useMemo` prend en second paramètre un tableau de dépendances qu'il surveille pour savoir quand se mettre à jour. :wink:

2023-03-30 07:12 UTC, quibaritaenperdresatrompe commented
Ton historique de commits doit être ré-écrit.. :wink:

2023-03-30 07:13 UTC, LeaCtrlup commented on src/routes/products.tsx
> +  const data = search<Product>(query.data, searchedTerm, [
ah ok, je l'ai pas vu très souvent et j'avais oublié ça visiblement. Je le rajoute du coup

2023-03-30 07:15 UTC, quibaritaenperdresatrompe commented on src/routes/products.tsx
> +  const [searchedTerm, setSearchedTerm] = useState("");
Est-ce que `searchTerms` serait mieux ?

2023-03-30 09:07 UTC, quibaritaenperdresatrompe requested changes

2023-03-30 09:07 UTC, quibaritaenperdresatrompe commented on src/routes/products.tsx
> +  const [searchedTerm, setSearchedTerm] = useState("");
Pourquoi mettre un pouce, résoudre la conversation, mais ne pas changer le nom ? :smile:

2023-03-30 09:07 UTC, quibaritaenperdresatrompe commented on src/routes/products.tsx
> +  const data = search<Product>(query.data, searchedTerm, [
Pourquoi résoudre la conversation alors que le `useMemo()` n'est pas implémenté ?

2023-03-30 09:07 UTC, quibaritaenperdresatrompe commented on src/utils/search.test.ts
> +describe("itIncludesTerms", () => {
Il manque des cas de tests non-passants notamment celui où il ne trouve pas de terme.

2023-03-30 09:07 UTC, quibaritaenperdresatrompe commented on src/utils/search.test.ts
> +  it("returns elements containing all searched key words", () => {
Ça ne retourne aucun élément, tu devrais décrire mieux ce test :wink:

2023-03-30 09:07 UTC, quibaritaenperdresatrompe commented on src/routes/products.tsx
> +  // const data = search(query.data, searchedTerms, ["title", "description"]);
Pourquoi ces commentaires ?

2023-03-30 09:07 UTC, quibaritaenperdresatrompe commented on src/routes/products.tsx
> +  let data;
Ce n'est pas comme ça qu'on utilise useMemo() mais plutôt comme cela :
```
const data = useMemo()
```

2023-03-30 09:07 UTC, quibaritaenperdresatrompe commented on src/routes/products.tsx
> +  const [searchedTerms, setSearchedTerms] = useState("");
Du coup tu ne veux pas le changer malgré ton :+1: sur la conversation précédente ?

2023-03-30 09:08 UTC, quibaritaenperdresatrompe requested changes

2023-03-30 09:08 UTC, quibaritaenperdresatrompe commented on src/routes/products.tsx
> +import { useMemo } from "react";
Tu devrais regrouper tes imports depuis "react", il y en a deux actuellement.

2023-03-30 09:10 UTC, quibaritaenperdresatrompe requested changes

2023-03-30 09:10 UTC, quibaritaenperdresatrompe commented on src/routes/products.tsx
> +  let data;
Y'a carrément une erreur sur GitHub donc tu dois l'avoir sur ton VSCode...
![image](https://user-images.githubusercontent.com/26886259/228787821-230ad816-5b55-40bb-8e94-0d1606ecd198.png)

2023-03-30 09:11 UTC, LeaCtrlup commented on src/routes/products.tsx
> +  // const data = search(query.data, searchedTerms, ["title", "description"]);
parce que je les ai oublié à force de switcher de code... C'est parce que mon code au dessus me met une erreur typescript, que je ne sais pas résoudre, il va peut etre falloir qu'on voir ça ensemble

2023-03-30 09:13 UTC, LeaCtrlup commented on src/routes/products.tsx
> +  const [searchedTerms, setSearchedTerms] = useState("");
mince j'ai ajouté le s à term(s) j'avais pas vu le search aussi

2023-03-30 09:17 UTC, LeaCtrlup commented on src/routes/products.tsx
> +  const [searchedTerm, setSearchedTerm] = useState("");
je l'ai changé, j'ai ajouté un s à term

2023-03-30 10:12 UTC, quibaritaenperdresatrompe requested changes

2023-03-30 13:11 UTC, merged

2023-03-30 13:15 UTC, quibaritaenperdresatrompe commented
:tada: This PR is included in version 1.26.0 :tada:

The release is available on [GitHub release](https://github.com/equipementmoderne/magasin-global/releases/tag/v1.26.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: